// ============================================================
// DeepSeek Tool Agent — Panel CSS (Editorial / Industrial)
// Extracted from panel.js for modularity
// ============================================================

function injectPanelCSS() {
  var s = document.getElementById('__ds-agent-css');
  if (s) return;
  s = document.createElement('style');
  s.id = '__ds-agent-css';
  s.textContent = [
    '/* ===== Design Tokens: Editorial / Industrial ===== */',
    ':root {',
    '  --ds-accent: oklch(0.65 0.18 70);',
    '  --ds-accent-dim: oklch(0.65 0.18 70 / 0.12);',
    '  --ds-accent-glow: oklch(0.65 0.18 70 / 0.22);',
    '  --ds-surface: oklch(0.985 0.002 90);',
    '  --ds-surface-raised: oklch(0.975 0.003 90);',
    '  --ds-surface-hover: oklch(0.955 0.005 90);',
    '  --ds-surface-active: oklch(0.93 0.008 90);',
    '  --ds-text: oklch(0.18 0.005 90);',
    '  --ds-text-secondary: oklch(0.44 0.012 90);',
    '  --ds-text-tertiary: oklch(0.60 0.010 90);',
    '  --ds-border: oklch(0.885 0.005 90);',
    '  --ds-border-hover: oklch(0.75 0.02 75);',
    '  --ds-error: oklch(0.52 0.20 25);',
    '  --ds-error-bg: oklch(0.52 0.20 25 / 0.08);',
    '  --ds-success: oklch(0.52 0.16 145);',
    '  --ds-success-bg: oklch(0.52 0.16 145 / 0.08);',
    '  --ds-info: oklch(0.48 0.14 240);',
    '  --ds-info-bg: oklch(0.48 0.14 240 / 0.08);',
    '  --ds-warn: oklch(0.60 0.15 80);',
    '  --ds-warn-bg: oklch(0.60 0.15 80 / 0.10);',
    '  --ds-shadow-1: 0 1px 2px oklch(0 0 0 / 0.04);',
    '  --ds-shadow-2: 0 2px 8px oklch(0 0 0 / 0.06);',
    '  --ds-shadow-3: 0 4px 16px oklch(0 0 0 / 0.10);',
    '  --ds-shadow-4: 0 8px 32px oklch(0 0 0 / 0.14);',
    '  --ds-radius-sm: 3px;',
    '  --ds-radius-md: 6px;',
    '  --ds-radius-lg: 10px;',
    '  --ds-radius-xl: 14px;',
    '  --ds-radius-full: 999px;',
    '  --ds-font: system-ui, -apple-system, "Segoe UI Variable", "SF Pro Text", sans-serif;',
    '  --ds-font-mono: "SF Mono", "Cascadia Code", "Fira Code", "Consolas", monospace;',
    '  --ds-fs-xs: 10px;',
    '  --ds-fs-sm: 11.5px;',
    '  --ds-fs-base: 13px;',
    '  --ds-fs-lg: 15px;',
    '  --ds-fs-xl: 18px;',
    '  --ds-ease: 0.12s ease;',
    '  --ds-ease-out: cubic-bezier(0.22, 0.61, 0.36, 1);',
    '}',

    '/* ===== Dark Mode ===== */',
    '@media (prefers-color-scheme: dark) {',
    '  :root {',
    '    --ds-surface: oklch(0.14 0.005 260);',
    '    --ds-surface-raised: oklch(0.17 0.006 260);',
    '    --ds-surface-hover: oklch(0.20 0.008 260);',
    '    --ds-surface-active: oklch(0.24 0.010 260);',
    '    --ds-text: oklch(0.90 0.003 260);',
    '    --ds-text-secondary: oklch(0.62 0.010 260);',
    '    --ds-text-tertiary: oklch(0.46 0.010 260);',
    '    --ds-border: oklch(0.26 0.008 260);',
    '    --ds-border-hover: oklch(0.38 0.02 75);',
    '    --ds-shadow-1: 0 1px 2px oklch(0 0 0 / 0.20);',
    '    --ds-shadow-2: 0 2px 8px oklch(0 0 0 / 0.28);',
    '    --ds-shadow-3: 0 4px 16px oklch(0 0 0 / 0.36);',
    '    --ds-shadow-4: 0 8px 32px oklch(0 0 0 / 0.44);',
    '  }',
    '}',

    '/* ===== Panel Container ===== */',
    '#__ds-agent-panel * { box-sizing: border-box; margin: 0; padding: 0; }',
    '#__ds-agent-panel {',
    '  position: fixed; bottom: 120px; right: 20px; z-index: 2147483640;',
    '  width: 760px; height: 520px; background: var(--ds-surface);',
    '  border: 1px solid var(--ds-border); border-radius: var(--ds-radius-xl);',
    '  font-family: var(--ds-font); font-size: var(--ds-fs-base);',
    '  color: var(--ds-text); display: none !important; overflow: hidden;',
    '  box-shadow: var(--ds-shadow-4);',
    '  letter-spacing: -0.01em;',
    '}',
    '#__ds-agent-panel.visible { display: flex !important; flex-direction: column; }',

    '/* ===== Header ===== */',
    '#__ds-header {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 10px 14px;',
    '  border-bottom: 1px solid var(--ds-border);',
    '  background: var(--ds-surface-raised); flex-shrink: 0;',
    '  cursor: grab; user-select: none;',
    '}',
    '#__ds-header:active { cursor: grabbing; }',
    '#__ds-header-left { display: flex; align-items: center; gap: 8px; }',
    '#__ds-logo {',
    '  font-size: var(--ds-fs-lg); font-weight: 800;',
    '  color: var(--ds-accent); letter-spacing: -0.02em;',
    '}',
    '#__ds-title { font-weight: 600; font-size: var(--ds-fs-base); }',
    '#__ds-version {',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary);',
    '  padding: 1px 6px; border-radius: var(--ds-radius-sm);',
    '  background: var(--ds-surface-hover);',
    '}',

    '/* ===== Status Indicator ===== */',
    '#__ds-status {',
    '  display: flex; align-items: center; gap: 6px;',
    '  padding: 3px 10px;',
    '  border-radius: var(--ds-radius-full);',
    '  background: var(--ds-surface-hover);',
    '  font-size: var(--ds-fs-xs);',
    '}',
    '#__ds-dot {',
    '  width: 7px; height: 7px; border-radius: 50%;',
    '  background: oklch(0.80 0.01 260);',
    '  transition: all 0.25s var(--ds-ease-out);',
    '}',
    '#__ds-dot.online {',
    '  background: var(--ds-success);',
    '  box-shadow: 0 0 6px var(--ds-success-bg);',
    '}',
    '#__ds-dot.offline {',
    '  background: var(--ds-error);',
    '  box-shadow: 0 0 6px var(--ds-error-bg);',
    '}',
    '#__ds-status-text { color: var(--ds-text-secondary); }',

    '#__ds-header-btns { display: flex; align-items: center; gap: 4px; }',
    '.ds-hbtn {',
    '  width: 32px; height: 32px; border: none;',
    '  border-radius: var(--ds-radius-md); background: none; cursor: pointer;',
    '  font-size: 18px; display: flex; align-items: center; justify-content: center;',
    '  color: var(--ds-text-tertiary); transition: all var(--ds-ease);',
    '}',
    '.ds-hbtn:hover { background: var(--ds-surface-hover); color: var(--ds-text); }',

    '/* ===== Body: Dual Column ===== */',
    '#__ds-body { display: flex; flex: 1; overflow: hidden; min-height: 0; }',
    '#__ds-col-left {',
    '  width: 55%; display: flex; flex-direction: column;',
    '  border-right: 1px solid var(--ds-border); overflow: hidden;',
    '}',
    '#__ds-col-right { width: 45%; display: flex; flex-direction: column; overflow: hidden; }',

    '/* ===== Left Column Tabs ===== */',
    '.ds-left-tabs {',
    '  display: flex; gap: 0; border-bottom: 1px solid var(--ds-border);',
    '  background: var(--ds-surface-raised); flex-shrink: 0;',
    '}',
    '.ds-left-tab {',
    '  flex: 1; padding: 9px 14px; border: none; background: none;',
    '  font-size: var(--ds-fs-sm); font-weight: 600; font-family: var(--ds-font);',
    '  color: var(--ds-text-tertiary); cursor: pointer; text-align: center;',
    '  border-bottom: 2px solid transparent;',
    '  transition: all var(--ds-ease); letter-spacing: 0.2px;',
    '}',
    '.ds-left-tab:hover {',
    '  color: var(--ds-text); background: var(--ds-surface-hover);',
    '}',
    '.ds-left-tab.active {',
    '  color: var(--ds-accent); border-bottom-color: var(--ds-accent);',
    '}',
    '.ds-left-panel {',
    '  display: none; flex-direction: column; flex: 1; overflow: hidden; min-height: 0;',
    '}',
    '.ds-left-panel.active { display: flex; }',

    '/* Column Headers */',
    '.ds-col-header {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 10px 14px;',
    '  border-bottom: 1px solid var(--ds-border); flex-shrink: 0;',
    '  background: var(--ds-surface);',
    '}',
    '.ds-col-title { font-size: var(--ds-fs-sm); font-weight: 700; color: var(--ds-text-tertiary); text-transform: uppercase; letter-spacing: 0.5px; }',
    '.ds-search-wrap { position: relative; width: 150px; }',
    '.ds-search-input {',
    '  width: 100%; padding: 5px 10px 5px 26px;',
    '  border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-full);',
    '  font-size: var(--ds-fs-sm); font-family: var(--ds-font);',
    '  background: var(--ds-surface); color: var(--ds-text);',
    '  outline: none; transition: border-color var(--ds-ease);',
    '}',
    '.ds-search-input:focus {',
    '  border-color: var(--ds-accent);',
    '  box-shadow: 0 0 0 3px var(--ds-accent-glow);',
    '}',
    '.ds-search-icon {',
    '  position: absolute; left: 9px; top: 50%; transform: translateY(-50%);',
    '  font-size: 11px; color: var(--ds-text-tertiary);',
    '}',
    '.ds-more-btn {',
    '  background: none; border: none; font-size: 17px; cursor: pointer;',
    '  color: var(--ds-text-tertiary); padding: 2px 6px;',
    '  border-radius: var(--ds-radius-sm); transition: all var(--ds-ease);',
    '}',
    '.ds-more-btn:hover { background: var(--ds-surface-hover); color: var(--ds-text); }',

    '/* ===== Tool Cards ===== */',
    '.ds-tool-list { padding: 6px 8px; display: flex; flex-direction: column; gap: 1px; }',
    '.ds-tool-card {',
    '  display: flex; align-items: center; gap: 10px;',
    '  padding: 9px 10px; border-radius: var(--ds-radius-md);',
    '  cursor: pointer; transition: background var(--ds-ease);',
    '}',
    '.ds-tool-card:hover { background: var(--ds-surface-hover); }',
    '.ds-tool-icon { font-size: 16px; width: 22px; text-align: center; flex-shrink: 0; }',
    '.ds-tool-info { flex: 1; min-width: 0; }',
    '.ds-tool-name {',
    '  font-size: var(--ds-fs-base); font-weight: 600;',
    '  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
    '}',
    '.ds-tool-desc {',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary);',
    '  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
    '  margin-top: 1px;',
    '}',
    '.ds-tool-mode {',
    '  font-size: var(--ds-fs-xs); font-weight: 650;',
    '  padding: 3px 10px; border-radius: var(--ds-radius-sm);',
    '  cursor: pointer; user-select: none; flex-shrink: 0;',
    '  transition: all var(--ds-ease); letter-spacing: 0.3px;',
    '}',
    '.ds-mode-auto { color: var(--ds-success); background: var(--ds-success-bg); }',
    '.ds-mode-manual { color: var(--ds-warn); background: var(--ds-warn-bg); }',
    '.ds-mode-off { color: var(--ds-text-tertiary); background: var(--ds-surface-hover); }',
    '.ds-tool-add {',
    '  font-size: 16px; color: var(--ds-text-tertiary);',
    '  cursor: pointer; width: 20px; text-align: center;',
    '}',

    '/* ===== Skills ===== */',
    '.ds-skills-list { padding: 6px 8px; }',
    '.ds-skill-row {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 9px 10px; border-radius: var(--ds-radius-md);',
    '  transition: background var(--ds-ease);',
    '}',
    '.ds-skill-row:hover { background: var(--ds-surface-hover); }',
    '.ds-skill-name { font-size: var(--ds-fs-base); font-weight: 550; }',
    '.ds-skill-toggle { display: flex; align-items: center; gap: 6px; cursor: pointer; }',
    '.ds-toggle-pill {',
    '  width: 34px; height: 20px; border-radius: var(--ds-radius-full);',
    '  position: relative; transition: background var(--ds-ease);',
    '  border: none; cursor: pointer;',
    '}',
    '.ds-toggle-pill.on { background: var(--ds-accent); }',
    '.ds-toggle-pill.off { background: oklch(0.78 0.01 260); }',
    '.ds-toggle-knob {',
    '  position: absolute; top: 2px; left: 2px;',
    '  width: 16px; height: 16px; border-radius: 50%;',
    '  background: #fff; transition: transform 0.18s var(--ds-ease-out);',
    '  box-shadow: 0 1px 2px oklch(0 0 0 / 0.15);',
    '}',
    '.ds-toggle-pill.on .ds-toggle-knob { transform: translateX(14px); }',
    '.ds-add-skill-btn {',
    '  display: flex; align-items: center; gap: 5px;',
    '  margin: 6px 8px; padding: 10px 12px;',
    '  border: 1px solid var(--ds-border); border-radius: var(--ds-radius-md);',
    '  font-size: var(--ds-fs-sm); color: var(--ds-text-secondary);',
    '  background: var(--ds-surface); cursor: pointer;',
    '  width: calc(100% - 16px);',
    '  font-family: var(--ds-font); transition: all var(--ds-ease);',
    '}',
    '.ds-add-skill-btn:hover {',
    '  background: var(--ds-surface-hover);',
    '  border-color: var(--ds-accent); color: var(--ds-accent);',
    '}',

    '/* ===== Right Column: Logs ===== */',
    '#__ds-log-tabs { display: flex; gap: 3px; padding: 8px 14px 0; }',
    '.ds-log-tab {',
    '  padding: 5px 13px; border: none; background: none;',
    '  font-size: var(--ds-fs-xs); font-weight: 550; font-family: var(--ds-font);',
    '  color: var(--ds-text-tertiary); cursor: pointer;',
    '  border-radius: var(--ds-radius-sm); transition: all var(--ds-ease);',
    '}',
    '.ds-log-tab:hover { background: var(--ds-surface-hover); color: var(--ds-text); }',
    '.ds-log-tab.active { background: var(--ds-accent); color: #fff; }',
    '.ds-log-toolbar {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 6px 14px;',
    '}',
    '.ds-log-tb-btn {',
    '  padding: 4px 12px; border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-sm);',
    '  background: var(--ds-surface); font-size: var(--ds-fs-xs);',
    '  cursor: pointer; color: var(--ds-text);',
    '  font-family: var(--ds-font); transition: all var(--ds-ease);',
    '}',
    '.ds-log-tb-btn:hover {',
    '  border-color: var(--ds-accent); background: var(--ds-accent-dim);',
    '}',
    '#__ds-log-area {',
    '  flex: 1; overflow-y: auto; padding: 6px 14px;',
    '  font-size: var(--ds-fs-xs); line-height: 1.7;',
    '  font-family: var(--ds-font);',
    '}',
    '.ds-log-entry {',
    '  padding: 2px 0; display: flex; gap: 6px;',
    '  border-bottom: 1px solid oklch(0 0 0 / 0.02);',
    '  transition: background var(--ds-ease);',
    '}',
    '.ds-log-entry:hover { background: var(--ds-surface-hover); }',
    '.ds-log-time { color: var(--ds-text-tertiary); flex-shrink: 0; }',
    '.ds-log-badge {',
    '  padding: 0 5px; border-radius: var(--ds-radius-sm);',
    '  font-size: 9px; font-weight: 700; flex-shrink: 0;',
    '  text-transform: uppercase; letter-spacing: 0.4px;',
    '}',
    '.ds-badge-info { background: var(--ds-info-bg); color: var(--ds-info); }',
    '.ds-badge-warn { background: var(--ds-warn-bg); color: var(--ds-warn); }',
    '.ds-badge-error { background: var(--ds-error-bg); color: var(--ds-error); }',
    '.ds-badge-success { background: var(--ds-success-bg); color: var(--ds-success); }',
    '.ds-log-msg { color: var(--ds-text); word-break: break-word; }',
    '.ds-log-scroll-btn {',
    '  display: flex; align-items: center; justify-content: center; gap: 4px;',
    '  padding: 5px; border-top: 1px solid var(--ds-border);',
    '  background: var(--ds-surface-raised);',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary);',
    '  cursor: pointer; transition: color var(--ds-ease);',
    '}',
    '.ds-log-scroll-btn.active { color: var(--ds-accent); }',

    '/* ===== Bottom Bar ===== */',
    '#__ds-bottom-bar {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 10px 14px;',
    '  border-top: 1px solid var(--ds-border);',
    '  background: var(--ds-surface); flex-shrink: 0;',
    '}',
    '#__ds-quick-btns { display: flex; gap: 6px; flex: 1; }',
    '#__ds-builtin-btns {',
    '  display: flex; gap: 6px; flex-shrink: 0;',
    '  padding-right: 10px; border-right: 1px solid var(--ds-border); margin-right: 10px;',
    '}',
    '.ds-qbtn-builtin {',
    '  border-color: var(--ds-accent); color: var(--ds-accent); font-weight: 600;',
    '}',
    '.ds-qbtn-builtin:hover {',
    '  background: var(--ds-accent-dim); border-color: oklch(0.70 0.18 70);',
    '}',
    '.ds-qbtn {',
    '  display: flex; align-items: center; gap: 5px;',
    '  padding: 7px 14px;',
    '  border: 1px solid var(--ds-border); border-radius: var(--ds-radius-full);',
    '  background: var(--ds-surface); font-size: var(--ds-fs-sm);',
    '  cursor: pointer; color: var(--ds-text); white-space: nowrap;',
    '  font-family: var(--ds-font); transition: all var(--ds-ease);',
    '  letter-spacing: -0.01em; line-height: 1;',
    '}',
    '.ds-qbtn:hover {',
    '  border-color: var(--ds-accent);',
    '  background: var(--ds-accent-dim);',
    '}',
    '.ds-qbtn-icon { font-size: 13px; }',
    '#__ds-status-line {',
    '  display: flex; align-items: center; gap: 6px;',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary);',
    '  flex-shrink: 0;',
    '}',
    '#__ds-status-line .ds-online { color: var(--ds-success); font-weight: 600; }',
    '.ds-edit-btn {',
    '  width: 30px; height: 30px; border: 1px solid var(--ds-border);',
    '  border-radius: 50%; background: none; cursor: pointer;',
    '  font-size: 13px; display: flex; align-items: center; justify-content: center;',
    '  color: var(--ds-text-tertiary); margin-left: 6px;',
    '  transition: all var(--ds-ease);',
    '}',
    '.ds-edit-btn:hover {',
    '  background: var(--ds-surface-hover); border-color: var(--ds-accent);',
    '}',

    '/* ===== File Explorer ===== */',
    '.ds-fe-tab {',
    '  padding: 4px 12px; border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-sm); font-size: var(--ds-fs-xs);',
    '  cursor: pointer; background: var(--ds-surface);',
    '  color: var(--ds-text-tertiary); transition: all var(--ds-ease);',
    '  font-family: var(--ds-font); white-space: nowrap;',
    '}',
    '.ds-fe-tab.active {',
    '  background: var(--ds-accent); color: #fff; border-color: var(--ds-accent);',
    '}',
    '.ds-fe-tab:hover:not(.active) {',
    '  border-color: var(--ds-accent); color: var(--ds-accent);',
    '}',
    '.ds-fe-refresh {',
    '  width: 32px; height: 32px; border: none;',
    '  border-radius: var(--ds-radius-md); background: none; cursor: pointer;',
    '  font-size: 15px; color: var(--ds-text-tertiary);',
    '  display: flex; align-items: center; justify-content: center;',
    '  transition: all var(--ds-ease); flex-shrink: 0;',
    '}',
    '.ds-fe-refresh:hover {',
    '  background: var(--ds-surface-hover); color: var(--ds-text);',
    '}',
    '#__ds-fe-current-path {',
    '  padding: 4px 12px; font-size: var(--ds-fs-xs);',
    '  color: var(--ds-text-tertiary); background: var(--ds-surface-raised);',
    '  border-bottom: 1px solid var(--ds-border);',
    '  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
    '  font-family: var(--ds-font-mono); flex-shrink: 0;',
    '}',
    '#__ds-file-tree { flex: 1; overflow-y: auto; padding: 2px 0; min-height: 0; }',
    '.__ds-file-item {',
    '  display: flex; align-items: center; gap: 6px;',
    '  padding: 5px 12px; cursor: pointer;',
    '  font-size: var(--ds-fs-sm);',
    '  transition: background var(--ds-ease);',
    '}',
    '.__ds-file-item:hover { background: var(--ds-surface-hover); }',
    '.__ds-file-selected { background: var(--ds-accent-dim) !important; }',
    '.__ds-file-icon { font-size: 14px; flex-shrink: 0; width: 18px; text-align: center; }',
    '.__ds-file-name {',
    '  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
    '  color: var(--ds-text);',
    '}',
    '.__ds-file-size {',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary);',
    '  flex-shrink: 0; margin-left: auto;',
    '}',
    '.__ds-file-loading, .__ds-file-error {',
    '  padding: 24px 16px; text-align: center;',
    '  color: var(--ds-text-secondary); font-size: var(--ds-fs-sm); line-height: 1.6;',
    '}',
    '#__ds-file-preview {',
    '  display: flex; flex-direction: column;',
    '  border-top: 1px solid var(--ds-border);',
    '  max-height: 180px; overflow: hidden; flex-shrink: 0;',
    '}',
    '#__ds-file-preview.__ds-hidden { display: none; }',
    '.__ds-preview-header {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 6px 12px;',
    '  background: var(--ds-surface-raised);',
    '  border-bottom: 1px solid var(--ds-border);',
    '  flex-shrink: 0;',
    '}',
    '.__ds-preview-title {',
    '  font-size: var(--ds-fs-xs); font-weight: 600;',
    '  color: var(--ds-text); font-family: var(--ds-font-mono);',
    '}',
    '.__ds-preview-close {',
    '  width: 26px; height: 26px; border: none; background: none;',
    '  cursor: pointer; font-size: 16px; color: var(--ds-text-tertiary);',
    '  border-radius: var(--ds-radius-md); display: flex;',
    '  align-items: center; justify-content: center;',
    '  transition: all var(--ds-ease);',
    '}',
    '.__ds-preview-close:hover {',
    '  background: var(--ds-surface-hover); color: var(--ds-text);',
    '}',
    '.__ds-preview-content {',
    '  flex: 1; overflow-y: auto; padding: 10px 12px;',
    '  font-family: var(--ds-font-mono); font-size: var(--ds-fs-xs);',
    '  line-height: 1.5; color: var(--ds-text);',
    '  white-space: pre-wrap; word-break: break-all;',
    '  margin: 0;',
    '}',

    '/* ===== Overlay Panels ===== */',
    '#__ds-tools-overlay, #__ds-skills-overlay, #__ds-config-overlay {',
    '  position: absolute; bottom: 44px; right: 8px;',
    '  width: 340px; max-height: 370px;',
    '  background: var(--ds-surface);',
    '  border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-lg);',
    '  box-shadow: var(--ds-shadow-4);',
    '  z-index: 10; display: none; flex-direction: column; overflow: hidden;',
    '  transform-origin: bottom right;',
    '  animation: ds-overlay-in 0.15s ease-out;',
    '}',
    '#__ds-tools-overlay.visible, #__ds-skills-overlay.visible, #__ds-config-overlay.visible { display: flex; }',
    '@keyframes ds-overlay-in {',
    '  from { opacity: 0; transform: scale(0.94); }',
    '  to { opacity: 1; transform: scale(1); }',
    '}',
    '.ds-overlay-header {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 8px 10px;',
    '  border-bottom: 1px solid var(--ds-border); flex-shrink: 0;',
    '  background: var(--ds-surface-raised); min-height: 36px;',
    '  font-weight: 600; font-size: var(--ds-fs-sm);',
    '}',
    '.ds-overlay-body { flex: 1; overflow-y: auto; padding: 8px; }',
    '#__ds-tools-overlay .ds-tool-list { flex: 1; overflow-y: auto; }',
    '#__ds-skills-overlay .ds-skills-list { flex: 1; overflow-y: auto; }',
    '#__ds-config-overlay .ds-config-body {',
    '  padding: 10px; flex: 1; overflow-y: auto;',
    '}',
    '#__ds-config-overlay .ds-config-body.no-padding { padding: 0; }',

    '/* ===== Toggle Buttons ===== */',
    '#__ds-toggle-btns { display: flex; gap: 5px; padding: 0 8px; }',
    '.ds-tbtn {',
    '  width: 34px; height: 34px; border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-md); background: var(--ds-surface);',
    '  cursor: pointer; font-size: 16px;',
    '  display: flex; align-items: center; justify-content: center;',
    '  color: var(--ds-text-tertiary);',
    '  transition: all var(--ds-ease); position: relative;',
    '}',
    '.ds-tbtn:hover {',
    '  background: var(--ds-surface-hover);',
    '  border-color: var(--ds-accent); color: var(--ds-accent);',
    '}',
    '.ds-tbtn.active {',
    '  background: var(--ds-accent); color: #fff;',
    '  border-color: var(--ds-accent);',
    '  box-shadow: 0 0 0 3px var(--ds-accent-glow);',
    '}',

    '/* ===== Pet Ball ===== */',
    '#__ds-pet-ball:active { cursor: grabbing; }',
    '#__ds-pet-ball.visible { transform: scale(0); pointer-events: none; }',

    '/* ===== Modal ===== */',
    '.ds-modal-overlay {',
    '  position: fixed; inset: 0;',
    '  background: oklch(0 0 0 / 0.30);',
    '  z-index: 2147483647; display: none;',
    '  align-items: center; justify-content: center;',
    '}',
    '.ds-modal-overlay.show { display: flex; padding: 20px; }',
    '.ds-modal {',
    '  background: var(--ds-surface);',
    '  border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-lg);',
    '  padding: 22px; width: 420px; max-height: 68vh;',
    '  overflow-y: auto; position: relative;',
    '  box-shadow: var(--ds-shadow-4); z-index: 1;',
    '  color: var(--ds-text);',
    '}',
    '.ds-modal-title {',
    '  font-size: var(--ds-fs-lg); font-weight: 650;',
    '  margin-bottom: 16px; color: var(--ds-text);',
    '}',
    '.ds-modal-actions {',
    '  display: flex; justify-content: flex-end; gap: 8px; margin-top: 16px;',
    '}',

    '/* ===== Form ===== */',
    '.ds-form-group { margin-bottom: 10px; }',
    '.ds-form-label {',
    '  display: block; font-size: var(--ds-fs-xs); font-weight: 550;',
    '  margin-bottom: 4px; color: var(--ds-text-secondary);',
    '}',
    '.ds-form-input {',
    '  width: 100%; padding: 7px 10px;',
    '  border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-sm);',
    '  font-size: var(--ds-fs-sm); font-family: var(--ds-font);',
    '  background: var(--ds-surface); color: var(--ds-text);',
    '  outline: none; transition: border-color var(--ds-ease);',
    '}',
    '.ds-form-input:focus {',
    '  border-color: var(--ds-accent);',
    '  box-shadow: 0 0 0 3px var(--ds-accent-glow);',
    '}',

    '/* ===== Buttons in panel ===== */',
    '.ds-btn {',
    '  padding: 6px 16px; border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-sm);',
    '  font-size: var(--ds-fs-sm); cursor: pointer;',
    '  font-family: var(--ds-font);',
    '  transition: all var(--ds-ease);',
    '}',
    '.ds-btn-primary {',
    '  background: var(--ds-accent); color: #fff; border-color: var(--ds-accent); font-weight: 600;',
    '}',
    '.ds-btn-primary:hover { opacity: 0.92; }',
    '.ds-btn-secondary {',
    '  background: var(--ds-surface); color: var(--ds-text);',
    '}',
    '.ds-btn-secondary:hover { background: var(--ds-surface-hover); }',
    '.ds-btn-sm { padding: 4px 11px; font-size: var(--ds-fs-xs); }',

    '/* ===== QA Editor ===== */',
    '.ds-qa-entry {',
    '  border: 1px solid var(--ds-border); padding: 10px;',
    '  border-radius: var(--ds-radius-sm); margin-bottom: 8px;',
    '}',

    '/* ===== Config ===== */',
    '.ds-config-group { margin-bottom: 10px; }',
    '.ds-config-group label {',
    '  display: block; font-size: var(--ds-fs-xs);',
    '  color: var(--ds-text-secondary); margin-bottom: 3px;',
    '}',
    '.ds-config-group input, .ds-config-group select {',
    '  width: 100%; padding: 7px 10px;',
    '  border: 1px solid var(--ds-border);',
    '  border-radius: var(--ds-radius-md);',
    '  font-size: var(--ds-fs-sm); font-family: var(--ds-font);',
    '  background: var(--ds-surface); color: var(--ds-text);',
    '  outline: none; transition: border-color var(--ds-ease);',
    '}',
    '.ds-config-group input:focus {',
    '  border-color: var(--ds-accent);',
    '  box-shadow: 0 0 0 3px var(--ds-accent-glow);',
    '}',
    '.ds-config-group input:hover:not(:focus) { border-color: var(--ds-border-hover); }',
    '.ds-toggle-label {',
    '  display: flex !important; align-items: center; gap: 8px; cursor: pointer;',
    '  font-size: var(--ds-fs-sm) !important; color: var(--ds-text) !important;',
    '}',
    '.ds-toggle-label input[type="checkbox"] {',
    '  width: 36px; height: 20px; appearance: none; -webkit-appearance: none;',
    '  background: oklch(0.78 0.01 260);',
    '  border-radius: 10px; position: relative; cursor: pointer;',
    '  transition: background var(--ds-ease);',
    '  border: none !important; padding: 0 !important; flex-shrink: 0;',
    '}',
    '.ds-toggle-label input[type="checkbox"]::before {',
    '  content: ""; position: absolute; top: 2px; left: 2px;',
    '  width: 16px; height: 16px; background: #fff; border-radius: 50%;',
    '  transition: transform 0.18s var(--ds-ease-out);',
    '}',
    '.ds-toggle-label input[type="checkbox"]:checked { background: var(--ds-accent); }',
    '.ds-toggle-label input[type="checkbox"]:checked::before { transform: translateX(16px); }',
    '.ds-toggle-text { font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary); }',

    '.ds-config-save { width: 100%; }',
    '.ds-config-save:hover { opacity: 0.92; }',
    '.ds-config-save:focus-visible { outline: 2px solid var(--ds-accent); outline-offset: 2px; }',

    '.ds-server-status-row {',
    '  display: flex; align-items: center; gap: 10px;',
    '  padding: 10px; background: var(--ds-surface-raised);',
    '  border-radius: var(--ds-radius-md); margin-bottom: 10px;',
    '  border: 1px solid var(--ds-border);',
    '}',
    '.ds-status-dot {',
    '  width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0;',
    '  background: oklch(0.80 0.01 260);',
    '  transition: all 0.25s var(--ds-ease-out);',
    '}',
    '.ds-status-dot.online {',
    '  background: var(--ds-success);',
    '  box-shadow: 0 0 6px var(--ds-success-bg);',
    '}',
    '#__ds-cfg-status-label {',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-secondary); flex: 1;',
    '}',
    '.ds-btn-start {',
    '  background: var(--ds-accent) !important; color: #fff !important;',
    '  border-color: var(--ds-accent) !important; flex-shrink: 0;',
    '}',
    '.ds-btn-start:disabled { opacity: 0.55; cursor: not-allowed; }',
    '.ds-btn-start.restart {',
    '  background: var(--ds-success) !important;',
    '  border-color: var(--ds-success) !important;',
    '}',

    '/* ===== SSE Badge ===== */',
    '.ds-sse-badge {',
    '  display: inline-block; padding: 1px 5px; border-radius: var(--ds-radius-sm);',
    '  background: var(--ds-success-bg); color: var(--ds-success);',
    '  font-size: 9px; font-weight: 700; letter-spacing: 0.4px;',
    '  margin-left: 6px; opacity: 0.4; transition: all 0.3s;',
    '  cursor: default; user-select: none;',
    '}',
    '.ds-sse-badge.active {',
    '  opacity: 1;',
    '  background: var(--ds-accent-dim); color: var(--ds-accent);',
    '  box-shadow: 0 0 8px var(--ds-accent-glow);',
    '  animation: ds-sse-pulse 2s ease-in-out infinite;',
    '}',
    '@keyframes ds-sse-pulse {',
    '  0%, 100% { box-shadow: 0 0 4px var(--ds-accent-glow); }',
    '  50% { box-shadow: 0 0 14px oklch(0.65 0.18 70 / 0.35); }',
    '}',

    '/* ===== Empty State ===== */',
    '.ds-empty-state {',
    '  padding: 24px 16px; text-align: center;',
    '  display: flex; flex-direction: column; align-items: center;',
    '  gap: 6px;',
    '}',
    '.ds-empty-icon { font-size: 28px; opacity: 0.4; }',
    '.ds-empty-text {',
    '  font-size: var(--ds-fs-sm); font-weight: 600;',
    '  color: var(--ds-text-secondary);',
    '}',
    '.ds-empty-hint {',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary);',
    '  max-width: 200px; line-height: 1.5;',
    '}',

    '/* ===== Log Detail & Count Bar ===== */',
    '.ds-log-entry { cursor: pointer; }',
    '.ds-log-entry.ds-log-expanded {',
    '  background: var(--ds-surface-hover);',
    '  border-radius: var(--ds-radius-sm);',
    '  padding: 4px 6px;',
    '}',
    '.ds-log-detail {',
    '  padding: 6px 0 2px 0;',
    '  font-family: var(--ds-font-mono); font-size: var(--ds-fs-xs);',
    '  color: var(--ds-text-secondary);',
    '  line-height: 1.5;',
    '  white-space: pre-wrap; word-break: break-word;',
    '  border-top: 1px solid var(--ds-border);',
    '  margin-top: 4px;',
    '}',
    '.ds-log-count-bar {',
    '  display: flex; gap: 8px; padding: 6px 14px;',
    '  border-top: 1px solid var(--ds-border);',
    '  flex-shrink: 0;',
    '}',
    '.ds-log-count {',
    '  font-size: var(--ds-fs-xs); color: var(--ds-text-tertiary);',
    '  font-weight: 550;',
    '}',
    '.ds-log-count-error { color: var(--ds-error); }',
    '.ds-log-count-warn { color: var(--ds-warn); }',

    '/* ===== Resize Handle ===== */',
    '#__ds-resize-handle {',
    '  position: absolute; bottom: 0; right: 0;',
    '  width: 14px; height: 14px; cursor: nwse-resize;',
    '  z-index: 10;',
    '  background: linear-gradient(135deg,',
    '    transparent 50%, var(--ds-border) 50%,',
    '    transparent 55%, var(--ds-border) 55%,',
    '    transparent 60%, var(--ds-border) 60%,',
    '    transparent 65%, var(--ds-border) 65%,',
    '    transparent 100%);',
    '}',

    '/* ===== Pet Ball Pulse ===== */',
    '#__ds-pet-dot {',
    '  position: absolute; top: 5px; right: 5px;',
    '  width: 8px; height: 8px; border-radius: 50%;',
    '  z-index: 2;',
    '  background: oklch(0.80 0.01 260);',
    '  transition: all 0.25s var(--ds-ease-out);',
    '}',
    '#__ds-pet-ball {',
    '  position: fixed; bottom: 20px; right: 20px; width: 52px; height: 52px;',
    '  border-radius: var(--ds-radius-lg);',
    '  background: var(--ds-surface-raised);',
    '  display: flex; align-items: center; justify-content: center;',
    '  cursor: grab; z-index: 2147483639;',
    '  box-shadow: var(--ds-shadow-3);',
    '  user-select: none; transition: transform 0.15s, box-shadow 0.3s;',
    '  font-size: 24px;',
    '  animation: ds-pet-float 3s ease-in-out infinite;',
    '}',
    '#__ds-pet-ball:hover {',
    '  box-shadow: var(--ds-shadow-4), 0 0 24px var(--ds-accent-glow);',
    '  transform: scale(1.08);',
    '  animation: none;',
    '}',
    '@keyframes ds-pet-float {',
    '  0%, 100% { transform: translateY(0); }',
    '  50% { transform: translateY(-4px); }',
    '}',

    '/* ===== Tool/Skills scroll fix ===== */',
    '#__ds-left-tools {',
    '  display: none; flex-direction: column; flex: 1; overflow: hidden; min-height: 0;',
    '}',
    '#__ds-left-tools.active { display: flex; }',
    '#__ds-left-tools .ds-tool-list {',
    '  flex: 1; overflow-y: auto; padding: 6px 8px;',
    '}',
  ].join('\n');
  document.head.appendChild(s);
}