// ============================================================
// DeepSeek Tool Agent — Panel CSS (Chromium-native styling)
// Extracted from panel.js for modularity
// ============================================================

function injectPanelCSS() {
  var s = document.getElementById('__ds-agent-css');
  if (s) return;
  s = document.createElement('style');
  s.id = '__ds-agent-css';
  s.textContent = [
    '/* ===== Chromium Design Tokens ===== */',
    ':root {',
    '  --cr-fallback-color-primary:#1a73e8;',
    '  --cr-fallback-color-on-primary:#fff;',
    '  --cr-fallback-color-surface:#fff;',
    '  --cr-fallback-color-surface-1:#f8f9fa;',
    '  --cr-fallback-color-surface-variant:#eee;',
    '  --cr-fallback-color-on-surface:#202124;',
    '  --cr-fallback-color-on-surface-subtle:#5f6368;',
    '  --cr-fallback-color-outline:#dadce0;',
    '  --cr-fallback-color-error:#d93025;',
    '  --cr-fallback-color-disabled-background:#f1f3f4;',
    '  --cr-fallback-color-disabled-foreground:#bdc1c6;',
    '  --google-blue-500:#4285f4;',
    '  --google-green-600:#1e8e3e;',
    '  --google-red-600:#d93025;',
    '  --google-yellow-400:#fcc934;',
    '  --google-grey-500:#9aa0a6;',
    '  --cr-space-1:4px;--cr-space-2:8px;--cr-space-3:12px;',
    '  --cr-space-4:16px;--cr-space-5:20px;--cr-space-6:24px;',
    '  --cr-space-8:32px;--cr-space-10:40px;',
    '  --cr-radius-xs:2px;--cr-radius-sm:4px;--cr-radius-md:8px;',
    '  --cr-radius-lg:16px;--cr-radius-xl:24px;--cr-radius-full:100px;',
    '  --cr-font-family:"Roboto","Segoe UI",system-ui,-apple-system,sans-serif;',
    '  --cr-font-size-xs:11px;--cr-font-size-sm:12px;--cr-font-size-md:13px;',
    '  --cr-font-size-base:14px;--cr-font-size-lg:16px;--cr-font-size-xl:20px;',
    '  --cr-elevation-1:0 1px 2px rgba(60,64,67,.3),0 1px 3px 1px rgba(60,64,67,.15);',
    '  --cr-elevation-2:0 1px 2px rgba(60,64,67,.3),0 2px 6px 2px rgba(60,64,67,.15);',
    '  --cr-elevation-3:0 1px 3px rgba(60,64,67,.3),0 4px 8px 3px rgba(60,64,67,.15);',
    '  --cr-elevation-5:0 1px 4px rgba(60,64,67,.3),0 8px 24px 6px rgba(60,64,67,.15);',
    '  --cr-transition-duration:80ms;',
    '}',
    '@media (prefers-color-scheme: dark) {',
    '  :root {',
    '    --cr-fallback-color-surface:#202124;',
    '    --cr-fallback-color-surface-1:#292a2d;',
    '    --cr-fallback-color-surface-variant:#3c4043;',
    '    --cr-fallback-color-on-surface:#e8eaed;',
    '    --cr-fallback-color-on-surface-subtle:#9aa0a6;',
    '    --cr-fallback-color-outline:#5f6368;',
    '    --cr-fallback-color-disabled-background:#2d2e30;',
    '    --cr-fallback-color-disabled-foreground:#80868b;',
    '  }',
    '  #__ds-agent-panel{background:#202124 !important;border-color:#5f6368}',
    '  #__ds-header{background:#292a2d;border-color:#5f6368}',
    '  #__ds-header-left,#__ds-header-left *{color:#e8eaed}',
    '  #__ds-col-left{border-color:#5f6368;background:#202124}',
    '  #__ds-col-right{background:#202124}',
    '  .ds-col-header{background:#202124;border-color:#5f6368}',
    '  .ds-col-title{color:#e8eaed}',
    '  .ds-tool-list{background:#202124}',
    '  .ds-tool-card{background:#202124}',
    '  .ds-tool-card:hover{background:#292a2d}',
    '  .ds-tool-name{color:#e8eaed}',
    '  .ds-tool-desc{color:#9aa0a6}',
    '  .ds-tool-mode.ds-mode-off{background:#3c4043;color:#9aa0a6}',
    '  .ds-skills-list{background:#202124}',
    '  .ds-skill-row{background:#202124}',
    '  .ds-skill-row:hover{background:#292a2d}',
    '  .ds-skill-name{color:#e8eaed}',
    '  .ds-search-input{background:#292a2d;color:#e8eaed;border-color:#5f6368}',
    '  #__ds-log-area{background:#202124;color:#e8eaed}',
    '  .ds-log-entry:hover{background:#292a2d}',
    '  .ds-log-msg{color:#e8eaed}',
    '  .ds-log-tab{color:#9aa0a6}',
    '  .ds-log-tab:hover{background:#292a2d;color:#e8eaed}',
    '  .ds-log-toolbar{background:#202124}',
    '  .ds-log-scroll-btn{background:#292a2d;border-color:#5f6368;color:#9aa0a6}',
    '  #__ds-bottom-bar{background:#202124;border-color:#5f6368}',
    '  .ds-qbtn{background:#292a2d;border-color:#5f6368;color:#e8eaed}',
    '  .ds-log-tb-btn{background:#292a2d;border-color:#5f6368;color:#e8eaed}',
    '  .ds-add-skill-btn{color:#9aa0a6;background:#292a2d;border-color:#5f6368}',
    '  .ds-add-skill-btn:hover{background:#3c4043;border-color:#8ab4f8;color:#8ab4f8}',
    '  .ds-more-btn{color:#9aa0a6}',
    '  #__ds-status{background:#292a2d;border-color:#5f6368}',
    '  #__ds-status-text{color:#9aa0a6}',
    '  #__ds-status-line{color:#9aa0a6}',
    '  .ds-toggle-pill.off{background:#3c4043}',
    '  .ds-form-input{background:#292a2d;color:#e8eaed;border-color:#5f6368}',
    '  .ds-form-label{color:#9aa0a6}',
    '  .ds-qa-entry{background:#292a2d;border-color:#5f6368}',
    '  .ds-btn-secondary{background:#292a2d;color:#e8eaed}',
    '  .ds-btn-secondary:hover{background:#3c4043}',
    '  .ds-modal{background:#202124;border-color:#5f6368;color:#e8eaed}',
    '  .ds-modal-title{color:#e8eaed}',
    '  .ds-badge-info{background:#1a3a5c;color:#8ab4f8}',
    '  .ds-badge-warn{background:#3c2e00;color:#fdd663}',
    '  .ds-badge-error{background:#3c1a1a;color:#f28b82}',
    '  .ds-badge-success{background:#1a3c1a;color:#81c995}',
    '  .ds-fe-tab{background:#292a2d;border-color:#5f6368;color:#9aa0a6}',
    '  .ds-fe-tab.active{background:var(--google-blue-500);color:#fff}',
    '  .ds-fe-tab:hover:not(.active){border-color:#8ab4f8;color:#8ab4f8}',
    '  #__ds-fe-current-path{background:#292a2d;border-color:#5f6368;color:#9aa0a6}',
    '  #__ds-file-tree{background:#202124}',
    '  .__ds-file-item:hover{background:#292a2d}',
    '  .__ds-file-selected{background:#1a3a5c !important}',
    '  .__ds-file-name{color:#e8eaed}',
    '  #__ds-file-preview{border-color:#5f6368}',
    '  #__ds-tools-overlay,#__ds-skills-overlay,#__ds-config-overlay{background:#202124;border-color:#5f6368}',
    '  .ds-overlay-header{background:#292a2d;border-color:#5f6368}',
    '  #__ds-pet-ball{background:#292a2d}',
    '  .ds-config-group input,.ds-config-group select{background:#292a2d;border-color:#5f6368;color:#e8eaed}',
    '  .ds-server-status-row{background:#292a2d;border-color:#5f6368}',
    '  #__ds-cfg-status-label{color:#9aa0a6}',
    '  .ds-tbtn{background:#292a2d;border-color:#5f6368;color:#9aa0a6}',
    '  .ds-tbtn:hover{background:#3c4043;border-color:#8ab4f8;color:#8ab4f8}',
    '}',

    '/* ===== Reset & Panel Container ===== */',
    '#__ds-agent-panel *{box-sizing:border-box;margin:0;padding:0}',
    '#__ds-agent-panel{',
    '  position:fixed;bottom:120px;right:20px;z-index:2147483640;',
    '  width:680px;height:440px;background:#fff;',
    '  border:1px solid #dadce0;border-radius:12px;',
    '  font-family:"Roboto","Segoe UI",system-ui,sans-serif;font-size:13px;',
    '  color:#202124;display:none !important;overflow:hidden;',
    '  box-shadow:0 4px 8px 3px rgba(60,64,67,.15),0 1px 3px 1px rgba(60,64,67,.3);',
    '}',
    '#__ds-agent-panel.visible{display:flex !important;flex-direction:column}',

    '/* ===== Header ===== */',
    '#__ds-header{',
    '  display:flex;align-items:center;justify-content:space-between;',
    '  padding:var(--cr-space-3) var(--cr-space-4);',
    '  border-bottom:1px solid var(--cr-fallback-color-outline);',
    '  background:var(--cr-fallback-color-surface-1);flex-shrink:0;',
    '  cursor:grab;user-select:none;',
    '}',
    '#__ds-header:active{cursor:grabbing}',
    '#__ds-header-left{display:flex;align-items:center;gap:var(--cr-space-2)}',
    '#__ds-logo{font-size:var(--cr-font-size-base);font-weight:700;color:var(--google-blue-500)}',
    '#__ds-title{font-weight:500;font-size:var(--cr-font-size-base)}',
    '#__ds-version{font-size:var(--cr-font-size-xs);color:var(--cr-fallback-color-on-surface-subtle);',
    '  padding:1px 6px;border-radius:var(--cr-radius-sm);background:var(--cr-fallback-color-surface-variant)}',
    '#__ds-status{',
    '  display:flex;align-items:center;gap:6px;padding:3px 10px;',
    '  border:1px solid var(--cr-fallback-color-outline);border-radius:var(--cr-radius-full);',
    '  font-size:var(--cr-font-size-xs);',
    '}',
    '#__ds-dot{width:8px;height:8px;border-radius:50%;background:var(--google-grey-500);transition:background .2s}',
    '#__ds-dot.online{background:var(--google-green-600)}',
    '#__ds-dot.offline{background:var(--google-red-600)}',
    '#__ds-status-text{color:var(--cr-fallback-color-on-surface-subtle)}',
    '#__ds-header-btns{display:flex;align-items:center;gap:2px}',
    '.ds-hbtn{',
    '  width:28px;height:28px;border:1px solid transparent;border-radius:var(--cr-radius-sm);',
    '  background:none;cursor:pointer;font-size:16px;display:flex;align-items:center;',
    '  justifyContent:center;color:var(--cr-fallback-color-on-surface-subtle);',
    '  transition:all var(--cr-transition-duration);',
    '}',
    '.ds-hbtn:hover{border-color:var(--cr-fallback-color-outline);background:var(--cr-fallback-color-surface-1)}',

    '/* ===== Body: Dual Column Layout ===== */',
    '#__ds-body{display:flex;flex:1;overflow:hidden;min-height:0}',
    '#__ds-col-left{width:55%;display:flex;flex-direction:column;border-right:1px solid var(--cr-fallback-color-outline);overflow-y:auto}',
    '#__ds-col-right{width:45%;display:flex;flex-direction:column;overflow:hidden}',

    '/* Column Headers */',
    '.ds-col-header{',
    '  display:flex;align-items:center;justify-content:space-between;',
    '  padding:var(--cr-space-3) var(--cr-space-4);',
    '  border-bottom:1px solid var(--cr-fallback-color-outline);flex-shrink:0;',
    '  background:var(--cr-fallback-color-surface);',
    '}',
    '.ds-col-title{font-size:var(--cr-font-size-lg);font-weight:500}',
    '.ds-search-wrap{position:relative;width:160px}',
    '.ds-search-input{',
    '  width:100%;padding:5px 10px 5px 28px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-full);font-size:var(--cr-font-size-sm);',
    '  background:var(--cr-fallback-color-surface);outline:none;',
    '}',
    '.ds-search-input:focus{border-color:var(--cr-fallback-color-primary)}',
    '.ds-search-icon{position:absolute;left:9px;top:50%;transform:translateY(-50%);font-size:12px;color:var(--cr-fallback-color-on-surface-subtle)}',
    '.ds-more-btn{background:none;border:none;font-size:18px;cursor:pointer;color:var(--cr-fallback-color-on-surface-subtle);padding:2px 6px;border-radius:var(--cr-radius-sm)}',
    '.ds-more-btn:hover{background:var(--cr-fallback-color-surface-1)}',

    /* Tool Cards */
    '.ds-tool-list{padding:var(--cr-space-2) var(--cr-space-3);display:flex;flex-direction:column;gap:1px}',
    '.ds-tool-card{',
    '  display:flex;align-items:center;gap:var(--cr-space-3);padding:var(--cr-space-3);',
    '  border-radius:var(--cr-radius-md);cursor:pointer;transition:background var(--cr-transition-duration);',
    '}',
    '.ds-tool-card:hover{background:var(--cr-fallback-color-surface-1)}',
    '.ds-tool-icon{font-size:18px;width:24px;text-align:center;flex-shrink:0}',
    '.ds-tool-info{flex:1;min-width:0}',
    '.ds-tool-name{font-size:var(--cr-font-size-base);font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
    '.ds-tool-desc{font-size:var(--cr-font-size-xs);color:var(--cr-fallback-color-on-surface-subtle);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:1px}',
    '.ds-tool-mode{',
    '  font-size:var(--cr-font-size-xs);font-weight:600;padding:2px 10px;border-radius:var(--cr-radius-sm);',
    '  cursor:pointer;user-select:none;flex-shrink:0;transition:all var(--cr-transition-duration);',
    '  letter-spacing:.5px;',
    '}',
    '.ds-mode-auto{color:var(--google-blue-500);background:#e8f0fe}',
    '.ds-mode-manual{color:var(--google-yellow-400);background:#fef7e0}',
    '.ds-mode-off{color:var(--cr-fallback-color-on-surface-subtle);background:var(--cr-fallback-color-surface-variant)}',
    '.ds-tool-add{font-size:18px;color:var(--cr-fallback-color-on-surface-subtle);cursor:pointer;width:20px;text-align:center}',

    /* Skills */
    '.ds-skills-list{padding:var(--cr-space-2) var(--cr-space-3)}',
    '.ds-skill-row{',
    '  display:flex;align-items:center;justify-content:space-between;',
    '  padding:var(--cr-space-3);border-radius:var(--cr-radius-md);',
    '  transition:background var(--cr-transition-duration);',
    '}',
    '.ds-skill-row:hover{background:var(--cr-fallback-color-surface-1)}',
    '.ds-skill-name{font-size:var(--cr-font-size-base);font-weight:500}',
    '.ds-skill-toggle{',
    '  display:flex;align-items:center;gap:6px;cursor:pointer;',
    '}',
    '.ds-toggle-pill{',
    '  width:32px;height:18px;border-radius:var(--cr-radius-full);position:relative;',
    '  transition:background var(--cr-transition-duration);border:none;cursor:pointer;',
    '}',
    '.ds-toggle-pill.on{background:var(--google-blue-500)}',
    '.ds-toggle-pill.off{background:var(--cr-fallback-color-surface-variant)}',
    '.ds-toggle-knob{',
    '  position:absolute;top:2px;width:14px;height:14px;border-radius:50%;',
    '  background:#fff;transition:transform var(--cr-transition-duration);box-shadow:0 1px 2px rgba(0,0,0,.2)',
    '}',
    '.ds-toggle-pill.on .ds-toggle-knob{transform:translateX(14px)}',
    '.ds-add-skill-btn{',
    '  display:flex;align-items:center;gap:4px;margin:var(--cr-space-2) var(--cr-space-3);',
    '  padding:var(--cr-space-3);border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-md);font-size:var(--cr-font-size-sm);color:var(--cr-fallback-color-on-surface-subtle);',
    '  background:var(--cr-fallback-color-surface);cursor:pointer;width:calc(100% - var(--cr-space-6));',
    '  transition:all var(--cr-transition-duration);',
    '}',
    '.ds-add-skill-btn:hover{',
    '  background:var(--cr-fallback-color-surface-1);border-color:var(--cr-fallback-color-primary);',
    '  color:var(--cr-fallback-color-on-surface);',
    '}',

    /* Right column: Logs */
    '#__ds-log-tabs{display:flex;gap:2px;padding:var(--cr-space-2) var(--cr-space-4) 0}',
    '.ds-log-tab{',
    '  padding:4px 12px;border:none;background:none;font-size:var(--cr-font-size-sm);',
    '  color:var(--cr-fallback-color-on-surface-subtle);cursor:pointer;border-radius:var(--cr-radius-sm);',
    '  font-weight:500;transition:all var(--cr-transition-duration);',
    '}',
    '.ds-log-tab:hover{background:var(--cr-fallback-color-surface-1)}',
    '.ds-log-tab.active{',
    '  background:var(--google-blue-500);color:#fff;',
    '}',
    '.ds-log-toolbar{',
    '  display:flex;align-items:center;justify-content:space-between;',
    '  padding:var(--cr-space-2) var(--cr-space-4);',
    '}',
    '.ds-log-tb-btn{',
    '  padding:3px 12px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-sm);background:var(--cr-fallback-color-surface);',
    '  font-size:var(--cr-font-size-xs);cursor:pointer;color:var(--cr-fallback-color-on-surface);',
    '}',
    '.ds-log-tb-btn:hover{background:var(--cr-fallback-color-surface-1);border-color:var(--cr-fallback-color-primary)}',
    '#__ds-log-area{',
    '  flex:1;overflow-y:auto;padding:var(--cr-space-2) var(--cr-space-4);',
    '  font-size:var(--cr-font-size-xs);line-height:1.65;font-family:var(--cr-font-family);',
    '}',
    '.ds-log-entry{padding:2px 0;border-bottom:1px solid transparent;display:flex;gap:6px}',
    '.ds-log-entry:hover{background:var(--cr-fallback-color-surface-1)}',
    '.ds-log-time{color:var(--cr-fallback-color-on-surface-subtle);flex-shrink:0}',
    '.ds-log-badge{',
    '  padding:0 6px;border-radius:2px;font-size:10px;font-weight:700;flex-shrink:0;',
    '  text-transform:uppercase;letter-spacing:.5px;',
    '}',
    '.ds-badge-info{background:#e8f0fe;color:var(--google-blue-500)}',
    '.ds-badge-warn{background:#fef7e0;color:#b06000}',
    '.ds-badge-error{background:#fce8e6;color:var(--google-red-600)}',
    '.ds-badge-success{background:#e6f4ea;color:var(--google-green-600)}',
    '.ds-log-msg{color:var(--cr-fallback-color-on-surface);word-break:break-word}',
    '.ds-log-scroll-btn{',
    '  display:flex;align-items:center;justify-content:center;gap:4px;',
    '  padding:4px;border-top:1px solid var(--cr-fallback-color-outline);',
    '  background:var(--cr-fallback-color-surface-1);font-size:var(--cr-font-size-xs);',
    '  color:var(--cr-fallback-color-on-surface-subtle);cursor:pointer;',
    '}',
    '.ds-log-scroll-btn.active{color:var(--google-blue-500)}',

    /* Bottom bar */
    '#__ds-bottom-bar{',
    '  display:flex;align-items:center;justify-content:space-between;',
    '  padding:var(--cr-space-2) var(--cr-space-4);',
    '  border-top:1px solid var(--cr-fallback-color-outline);',
    '  background:var(--cr-fallback-color-surface);flex-shrink:0;',
    '}',
    '#__ds-quick-btns{display:flex;gap:6px;flex:1}',
    '#__ds-builtin-btns{display:flex;gap:6px;flex-shrink:0;padding-right:8px;border-right:1px solid var(--cr-fallback-color-outline);margin-right:8px;}',
    '.ds-qbtn-builtin{border-color:var(--google-blue-500);color:var(--google-blue-500);font-weight:500}',
    '.ds-qbtn-builtin:hover{background:rgba(26,115,232,0.08);border-color:var(--google-blue-600)}',
    '.ds-qbtn{',
    '  display:flex;align-items:center;gap:4px;padding:5px 12px;',
    '  border:1px solid var(--cr-fallback-color-outline);border-radius:var(--cr-radius-full);',
    '  background:var(--cr-fallback-color-surface);font-size:var(--cr-font-size-xs);',
    '  cursor:pointer;color:var(--cr-fallback-color-on-surface);white-space:nowrap;',
    '  transition:all var(--cr-transition-duration);',
    '}',
    '.ds-qbtn:hover{border-color:var(--cr-fallback-color-primary);background:#e8f0fe}',
    '.ds-qbtn-icon{font-size:13px}',
    '#__ds-status-line{',
    '  display:flex;align-items:center;gap:6px;font-size:var(--cr-font-size-xs);',
    '  color:var(--cr-fallback-color-on-surface-subtle);flex-shrink:0;',
    '}',
    '#__ds-status-line .ds-online{color:var(--google-green-600);font-weight:600}',
    '.ds-edit-btn{',
    '  width:26px;height:26px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:50%;background:none;cursor:pointer;font-size:12px;',
    '  display:flex;align-items:center;justify-content:center;',
    '  color:var(--cr-fallback-color-on-surface-subtle);margin-left:6px;',
    '}',
    '.ds-edit-btn:hover{background:var(--cr-fallback-color-surface-1)}',

    '/* ===== File Explorer ===== */',
    '.ds-fe-tab{',
    '  padding:3px 10px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-sm);font-size:var(--cr-font-size-xs);',
    '  cursor:pointer;background:var(--cr-fallback-color-surface);',
    '  color:var(--cr-fallback-color-on-surface-subtle);transition:all var(--cr-transition-duration);',
    '  font-family:inherit;white-space:nowrap;',
    '}',
    '.ds-fe-tab.active{',
    '  background:var(--google-blue-500);color:#fff;border-color:var(--google-blue-500);',
    '}',
    '.ds-fe-tab:hover:not(.active){border-color:var(--cr-fallback-color-primary);color:var(--cr-fallback-color-primary)}',
    '.ds-fe-refresh{',
    '  width:28px;height:28px;border:1px solid transparent;',
    '  border-radius:var(--cr-radius-sm);background:none;cursor:pointer;',
    '  font-size:14px;color:var(--cr-fallback-color-on-surface-subtle);',
    '  display:flex;align-items:center;justify-content:center;',
    '  transition:all var(--cr-transition-duration);flex-shrink:0;',
    '}',
    '.ds-fe-refresh:hover{background:var(--cr-fallback-color-surface-1);border-color:var(--cr-fallback-color-outline)}',
    '#__ds-fe-current-path{',
    '  padding:4px 12px;font-size:10px;color:var(--cr-fallback-color-on-surface-subtle);',
    '  background:var(--cr-fallback-color-surface-1);',
    '  border-bottom:1px solid var(--cr-fallback-color-outline);',
    '  white-space:nowrap;overflow:hidden;text-overflow:ellipsis;',
    '  font-family:"Cascadia Code","Fira Code","Consolas",monospace;',
    '}',
    '#__ds-file-tree{',
    '  flex:1;overflow-y:auto;padding:2px 0;min-height:0;',
    '}',
    '.__ds-file-item{',
    '  display:flex;align-items:center;gap:6px;padding:5px 12px;',
    '  cursor:pointer;transition:background var(--cr-transition-duration);',
    '  font-size:var(--cr-font-size-sm);',
    '}',
    '.__ds-file-item:hover{background:var(--cr-fallback-color-surface-1)}',
    '.__ds-file-selected{background:#e8f0fe !important}',
    '.__ds-file-icon{font-size:14px;flex-shrink:0;width:18px;text-align:center}',
    '.__ds-file-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--cr-fallback-color-on-surface)}',
    '.__ds-file-size{font-size:10px;color:var(--cr-fallback-color-on-surface-subtle);flex-shrink:0;margin-left:auto}',
    '.__ds-file-loading,.__ds-file-error{',
    '  padding:24px 16px;text-align:center;color:var(--cr-fallback-color-on-surface-subtle);',
    '  font-size:var(--cr-font-size-sm);line-height:1.6;',
    '}',
    '#__ds-file-preview{',
    '  display:flex;flex-direction:column;border-top:1px solid var(--cr-fallback-color-outline);',
    '  max-height:180px;overflow:hidden;flex-shrink:0;',
    '}',
    '#__ds-file-preview.__ds-hidden{display:none}',

    '/* ===== Overlay Panels (Tools, Skills, Config) ===== */',
    '#__ds-tools-overlay,#__ds-skills-overlay,#__ds-config-overlay{',
    '  position:absolute;bottom:44px;right:8px;',
    '  width:340px;max-height:360px;background:var(--cr-fallback-color-surface);',
    '  border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-lg);box-shadow:var(--cr-elevation-5);',
    '  z-index:10;display:none;flex-direction:column;overflow:hidden;',
    '  transform-origin:bottom right;animation:ds-overlay-in .15s ease-out;',
    '}',
    '#__ds-tools-overlay.visible,#__ds-skills-overlay.visible,#__ds-config-overlay.visible{display:flex}',
    '@keyframes ds-overlay-in{',
    '  from{opacity:0;transform:scale(.92)}',
    '  to{opacity:1;transform:scale(1)}',
    '}',
    '.ds-overlay-header{',
    '  display:flex;align-items:center;justify-content:space-between;',
    '  padding:var(--cr-space-2) var(--cr-space-3);',
    '  border-bottom:1px solid var(--cr-fallback-color-outline);flex-shrink:0;',
    '  background:var(--cr-fallback-color-surface-1);min-height:36px;',
    '}',
    '.ds-overlay-body{',
    '  flex:1;overflow-y:auto;padding:var(--cr-space-3);',
    '}',
    '#__ds-tools-overlay .ds-tool-list{flex:1;overflow-y:auto}',
    '#__ds-skills-overlay .ds-skills-list{flex:1;overflow-y:auto}',
    '#__ds-config-overlay .ds-config-body{padding:var(--cr-space-3);flex:1;overflow-y:auto}',
    '#__ds-config-overlay .ds-config-body.no-padding{padding:0}',

    '/* ===== Toggle Buttons ===== */',
    '#__ds-toggle-btns{',
    '  display:flex;gap:4px;padding:0 8px;',
    '}',
    '.ds-tbtn{',
    '  width:30px;height:30px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-sm);background:var(--cr-fallback-color-surface);',
    '  cursor:pointer;font-size:15px;display:flex;align-items:center;justify-content:center;',
    '  color:var(--cr-fallback-color-on-surface-subtle);',
    '  transition:all var(--cr-transition-duration);position:relative;',
    '}',
    '.ds-tbtn:hover{background:var(--cr-fallback-color-surface-1);border-color:var(--cr-fallback-color-primary);color:var(--cr-fallback-color-primary)}',
    '.ds-tbtn.active{',
    '  background:var(--google-blue-500);color:#fff;border-color:var(--google-blue-500);',
    '  box-shadow:0 0 0 3px rgba(66,133,244,.25);',
    '}',

    /* Pet ball */
    '#__ds-pet-ball{',
    '  position:fixed;bottom:20px;right:20px;width:48px;height:48px;',
    '  border-radius:12px;background:var(--cr-fallback-color-surface-1);',
    '  display:flex;align-items:center;justify-content:center;',
    '  cursor:grab;z-index:2147483639;',
    '  box-shadow:0 2px 6px 2px rgba(60,64,67,.15),0 1px 3px 1px rgba(60,64,67,.3);',
    '  user-select:none;transition:transform .15s;overflow:hidden;',
    '}',
    '#__ds-pet-dot{',
    '  position:absolute;top:2px;right:2px;width:8px;height:8px;',
    '  border-radius:50%;background:var(--cr-fallback-color-disabled-foreground);z-index:1;',
    '}',
    '#__ds-pet-ball:active{cursor:grabbing}',
    '#__ds-pet-ball.visible{transform:scale(0);pointer-events:none}',

    /* Modal */
    '.ds-modal-overlay{',
    '  position:fixed;inset:0;background:rgba(0,0,0,.35);z-index:2147483647;',
    '  display:none;align-items:center;justify-content:center;',
    '}',
    '.ds-modal-overlay.show{display:flex;padding:20px}',
    '.ds-modal{',
    '  background:var(--cr-fallback-color-surface);border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-lg);padding:var(--cr-space-5);width:420px;max-height:70vh;',
    '  overflow-y:auto;position:relative;box-shadow:var(--cr-elevation-5);z-index:1;',
    '}',
    '.ds-modal-title{font-size:var(--cr-font-size-lg);font-weight:500;margin-bottom:var(--cr-space-4)}',
    '.ds-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:var(--cr-space-4)}',
    '.ds-form-group{margin-bottom:var(--cr-space-3)}',
    '.ds-form-label{display:block;font-size:var(--cr-font-size-xs);font-weight:500;margin-bottom:4px;color:var(--cr-fallback-color-on-surface-subtle)}',
    '.ds-form-input{',
    '  width:100%;padding:7px 10px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-sm);font-size:var(--cr-font-size-sm);',
    '  background:var(--cr-fallback-color-surface);outline:none;font-family:inherit;',
    '}',
    '.ds-form-input:focus{border-color:var(--cr-fallback-color-primary)}',
    '.ds-btn{',
    '  padding:6px 16px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-sm);font-size:var(--cr-font-size-sm);cursor:pointer;',
    '  font-family:inherit;transition:all var(--cr-transition-duration);',
    '}',
    '.ds-btn-primary{background:var(--google-blue-500);color:#fff;border-color:var(--google-blue-500)}',
    '.ds-btn-secondary{background:var(--cr-fallback-color-surface);color:var(--cr-fallback-color-on-surface)}',
    '.ds-btn-secondary:hover{background:var(--cr-fallback-color-surface-1)}',
    '.ds-btn-sm{padding:4px 12px;font-size:var(--cr-font-size-xs)}',
    '.ds-qa-entry{border:1px solid var(--cr-fallback-color-outline);padding:var(--cr-space-3);border-radius:var(--cr-radius-sm);margin-bottom:var(--cr-space-2)}',
    '.ds-config-group{margin-bottom:var(--cr-space-3)}',
    '.ds-config-group label{display:block;font-size:var(--cr-font-size-xs);color:var(--cr-fallback-color-on-surface-subtle);margin-bottom:2px}',
    '.ds-config-group input,.ds-config-group select{',
    '  width:100%;padding:7px 10px;border:1px solid var(--cr-fallback-color-outline);',
    '  border-radius:var(--cr-radius-md);font-size:var(--cr-font-size-sm);',
    '  background:var(--cr-fallback-color-surface);color:var(--cr-fallback-color-on-surface);',
    '  font-family:inherit;outline:none;transition:border-color var(--cr-transition-duration);',
    '}',
    '.ds-config-group input:focus{border-color:var(--cr-fallback-color-primary)}',
    '.ds-config-group input:hover:not(:focus){border-color:var(--cr-fallback-color-on-surface-subtle)}',
    '.ds-toggle-label{display:flex!important;align-items:center;gap:8px;cursor:pointer;font-size:var(--cr-font-size-sm)!important;color:var(--cr-fallback-color-on-surface)!important}',
    '.ds-toggle-label input[type="checkbox"]{',
    '  width:36px;height:20px;appearance:none;-webkit-appearance:none;',
    '  background:var(--cr-fallback-color-disabled-foreground);',
    '  border-radius:10px;position:relative;cursor:pointer;',
    '  transition:background var(--cr-transition-duration);',
    '  border:none!important;padding:0!important;flex-shrink:0;',
    '}',
    '.ds-toggle-label input[type="checkbox"]::before{content:"";position:absolute;top:2px;left:2px;width:16px;height:16px;background:#fff;border-radius:50%;transition:transform var(--cr-transition-duration)}',
    '.ds-toggle-label input[type="checkbox"]:checked{background:var(--google-blue-500)}',
    '.ds-toggle-label input[type="checkbox"]:checked::before{transform:translateX(16px)}',
    '.ds-toggle-text{font-size:var(--cr-font-size-xs);color:var(--cr-fallback-color-on-surface-subtle)}',
    '.ds-config-save{width:100%}',
    '.ds-config-save:hover{opacity:.92}',
    '.ds-config-save:focus-visible{outline:2px solid var(--cr-fallback-color-primary);outline-offset:2px}',
    '.ds-server-status-row{',
    '  display:flex;align-items:center;gap:var(--cr-space-3);padding:var(--cr-space-3);',
    '  background:var(--cr-fallback-color-surface-1);border-radius:var(--cr-radius-md);',
    '  margin-bottom:var(--cr-space-3);border:1px solid var(--cr-fallback-color-outline);',
    '}',
    '.ds-status-dot{',
    '  width:8px;height:8px;border-radius:50%;flex-shrink:0;',
    '  background:var(--cr-fallback-color-disabled-foreground);',
    '  transition:background var(--cr-transition-duration);',
    '}',
    '.ds-status-dot.online{background:var(--google-green-600);box-shadow:0 0 6px rgba(30,142,62,.35)}',
    '#__ds-cfg-status-label{',
    '  font-size:var(--cr-font-size-xs);color:var(--cr-fallback-color-on-surface-subtle);flex:1;',
    '}',
    '.ds-btn-start{',
    '  background:var(--google-blue-500)!important;color:#fff!important;',
    '  border-color:var(--google-blue-500)!important;flex-shrink:0;',
    '}',
    '.ds-btn-start:disabled{opacity:.6;cursor:not-allowed}',
    '.ds-btn-start.restart{background:var(--google-green-600)!important;border-color:var(--google-green-600)!important}',
    '.ds-sse-badge{',
    '  display:inline-block;padding:1px 6px;border-radius:4px;',
    '  background:rgba(91,138,74,0.12);color:#5b8a4a;',
    '  font-size:9px;font-weight:700;letter-spacing:0.5px;',
    '  margin-left:8px;opacity:0.5;transition:all .3s;',
    '  cursor:default;user-select:none;',
    '}',
    '.ds-sse-badge.active{',
    '  opacity:1;',
    '  background:rgba(138,180,248,0.18);color:#8ab4f8;',
    '  box-shadow:0 0 8px rgba(138,180,248,0.3);',
    '  animation:ds-sse-pulse 2s ease-in-out infinite;',
    '}',
    '@keyframes ds-sse-pulse{',
    '  0%,100%{box-shadow:0 0 4px rgba(138,180,248,0.2)}',
    '  50%{box-shadow:0 0 12px rgba(138,180,248,0.5)}',
    '}',
  ].join('\n');
  document.head.appendChild(s);
}